apiVersion: v1
kind: Service
metadata:
  name: tls-server-svc
spec:
  # loadBalancerIP:  13.70.200.12
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - name: tls-port
    port: 49665
  selector:
    app: tls-server
