apiVersion: apps/v1
kind: Deployment
metadata:
  name: tls-server
spec:
  selector:
    matchLabels:
      app: tls-server
  replicas: 2
  template:
    metadata:
      labels:
        app: tls-server
    spec:
      containers:
      - name: tls-server
        image: argmarios/tls_server:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1.50"
            memory: "512Mi"
          requests:
            cpu: "1.50"
            memory: "512Mi"
        readinessProbe:
          exec:
            command:
            - /bin/true
        livenessProbe:
          exec:
            command:
            - /bin/true
      # nodeSelector:
      #   disktype: extra
      securityContext:
        runAsUser: 1000