apiVersion: apps/v1
kind: Deployment
metadata:
  name: stun-client
spec:
  selector:
    matchLabels:
      app: stun-client
  replicas: 5
  template:
    metadata:
      labels:
        app: stun-client
    spec:
      containers:
      - name: stun-client
        image: argmarios/tcp-client:0.1.11:latest
        imagePullPolicy: Always
        env:
        - name: TCP_SERVER_IP
          value: "40.113.4.234"
        - name: TCP_SERVER_PORT
          value: "49665"
        - name: TCP_CLIENT_COUNT
          value: "6000"
        resources:
          limits:
            cpu: "2.00"
            memory: "2048Mi"
          requests:
            cpu: "2.00"
            memory: "2048Mi"
        readinessProbe:
          exec:
            command:
            - /bin/true
        livenessProbe:
          exec:
            command:
            - /bin/true
      securityContext:
        runAsUser: 1000
